<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.oliviercailloux</groupId>
    <artifactId>pom</artifactId>
    <version>0.0.30</version>
  </parent>
  <name>GitJFS filter</name>
  <groupId>io.github.oliviercailloux.git</groupId>
  <artifactId>gitjfs-filter</artifactId>
  <version>0.0.7-SNAPSHOT</version>
  <properties>
    <github-repository>GitJFS-filter</github-repository>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.github.oliviercailloux</groupId>
      <artifactId>jaris</artifactId>
      <version>0.0.42</version>
    </dependency>
    <dependency>
      <groupId>io.github.oliviercailloux.git</groupId>
      <artifactId>gitjfs</artifactId>
      <version>0.0.10</version>
    </dependency>
    <!-- For GitFilteringFs -->
    <dependency>
      <groupId>org.eclipse.jgit</groupId>
      <artifactId>org.eclipse.jgit</artifactId>
      <version>7.3.0.202506031305-r</version>
    </dependency>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-core</artifactId>
      <version>1.5.2</version>
    </dependency>
    <dependency>
      <groupId>org.jgrapht</groupId>
      <artifactId>jgrapht-guava</artifactId>
      <version>1.5.2</version>
    </dependency>
    
    <dependency>
      <groupId>io.github.oliviercailloux.git</groupId>
      <artifactId>git-common</artifactId>
      <version>0.0.5</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.oliviercailloux.git</groupId>
      <artifactId>git-factory</artifactId>
      <version>0.0.7</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>5.8.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
